services:
  db:
    image: postgres:18.1-trixie
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_USER: stride
      POSTGRES_PASSWORD: stride
      POSTGRES_DB: stride

volumes:
  db:
